<?php

namespace AppBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
    public function AreaLegalClientes($id = null)
    {
        $query = $this->getEntityManager();

        if ($id) {
            $result = $query
                ->createQuery('SELECT c FROM AppBundle:Cliente c JOIN c.tramites t JOIN t.trabajador w WHERE w.id=:id ORDER BY c.nombre ASC')
                ->setParameter('id', $id)
                ->getResult();
        } else {
            $result = $query
                ->createQuery('SELECT c FROM AppBundle:Cliente c JOIN c.tramites t JOIN t.trabajador w ORDER BY c.nombre ASC')
                ->getResult();
        }

        return $result;
    }

    public function ControlFondoClientes()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT c FROM AppBundle:Cliente c JOIN c.arrendamientos a WHERE a.isBaja=FALSE ORDER BY c.nombre ASC')
            ->getResult();
    }

    public function reporteXClienteOperaciones(){
        $a = $this->getEntityManager()
            ->createQuery('SELECT COUNT(c) FROM AppBundle:Cliente c JOIN c.arrendamientos a')
            ->getSingleScalarResult();
        $t = $this->getEntityManager()
            ->createQuery('SELECT COUNT(c) FROM AppBundle:Cliente c JOIN c.tramites t')
            ->getSingleScalarResult();

        return [$a, $t];
    }
}
