<?php

namespace AppBundle\Repository;

/**
 * EntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadRepository extends \Doctrine\ORM\EntityRepository
{
}
