<?php

namespace AppBundle\Repository;

/**
 * EscalaSalarialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscalaSalarialRepository extends \Doctrine\ORM\EntityRepository
{
}
