<?php

namespace AppBundle\Repository;

/**
 * EscolaridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscolaridadRepository extends \Doctrine\ORM\EntityRepository
{
}
