<?php

namespace AppBundle\Repository;

/**
 * IntegracionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntegracionRepository extends \Doctrine\ORM\EntityRepository
{
}
