# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
          - { name: twig.extension }

    app.form.type.trabajador:
        class: AppBundle\Form\Type\TrabajadorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: form.type }

    app.utils:
            class: AppBundle\Utils\Utils
            arguments: ["@doctrine.orm.entity_manager"]
            tags:
              - { name: app.utils }

    app.twig_extension:
        class: AppBundle\Twig\DateCompare
        public: false
        tags:
          - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
